### ISSUE TITLE
Issue with RAxML-NG not properly logged

### ISSUE THREAD

**Issue by tschuelia** [wiegertj/EBG#1]
If something goes wrong with the RAxML-NG Parsimony tree computation I get the following error: `TypeError: Logger.error() missing 1 required positional argument: 'msg'`. This is caused by this line:  
https://github.com/wiegertj/EBG/blob/e31cfc299acb231a48b52613a7e775b712138de6/EBG/Features/feature_computer.py#L572

I guess it would be helpful to add a hint as of why it failed (log the exception and maybe point to the RAxML-NG log file) :)

**Comment by wiegertj** [comment]
Thanks for pointing that out, fixed with release 0.12.1
